// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://quibvppxriibzfvhrhwv.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1aWJ2cHB4cmlpYnpmdmhyaHd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTE3NjMsImV4cCI6MjA3NDEyNzc2M30.-7fTNHTnidfohrUhSJ3_5vXdDOXO_G5X-jq_M46QHlQ';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
